Repository Y3-S1-project-group/Medicare-frontend, pull requests merged in 2024-10, with the labels that each got.

#1 frontend of Staff management added
  package-lock.json
  package.json
  src/App.jsx
  src/Styles/Footer.css
  src/Styles/display.css
  src/components/AddStaffMember/AddStaffMember.jsx
  src/components/DeleteStaffMember/DeleteStaffMember.jsx
  src/components/DisplayStaffMember/DisplayStaffMembers.jsx
  src/components/UpdateStaffMember/UpdateStaffMember.jsx
  src/pages/AdminStaffMember/AdminStaffMember.jsx
Labels: documentation

#2 frontend of Staff management added
  package-lock.json
  package.json
  src/App.jsx
  src/Styles/Footer.css
  src/Styles/display.css
  src/components/AddStaffMember/AddStaffMember.jsx
  src/components/DeleteStaffMember/DeleteStaffMember.jsx
  src/components/DisplayStaffMember/DisplayStaffMembers.jsx
  src/components/UpdateStaffMember/UpdateStaffMember.jsx
  src/pages/AdminStaffMember/AdminStaffMember.jsx
Labels: documentation

#5 It22352576medicine
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Report genaration.png
  src/assets/logo.png
  src/components/SideNavBar/SideNavBar.jsx
  src/index.css
  src/pages/Report/CombinedHospitalCharts.jsx
  src/pages/Report/Report.jsx
  src/pages/Shift/Shift.jsx
Labels: documentation

#7 add payment page and refactor codes
  src/components/AppoinmentSystem/Appoinments.jsx
  src/components/AppoinmentSystem/BookAppointment.jsx
  src/components/AppoinmentSystem/Navbar.jsx
  src/components/AppoinmentSystem/PaymentPage.jsx
Labels: feature

#8 It22352576medicine
  package-lock.json
  package.json
  src/assets/logo.png
  src/components/ReportDetails/CombinedHospitalCharts.jsx
  src/components/ReportDetails/Popup.jsx
  src/pages/Report/CombinedHospitalCharts.jsx
  src/pages/Report/HospitalReportPDFGenerator.jsx
  src/pages/Report/Report.jsx
  src/pages/Shift/Shift.jsx
Labels: feature

#9 It22202468/user management
  src/App.jsx
  src/assets/react.svg
  src/components/AddStaffMember/AddStaffMember.jsx
  src/pages/UserManagement/AdminDashboard.jsx
  src/pages/UserManagement/DoctorDashboard.jsx
  src/pages/UserManagement/Login.jsx
  src/pages/UserManagement/NurseDashboard.jsx
  src/pages/UserManagement/PatientDashboard.jsx
  src/pages/UserManagement/Signup.jsx
Labels: good first issue

#11 change some thing
  src/components/AppoinmentSystem/BookAppointment.jsx
Labels: feature

#12 It22114808/appoinment system
  src/components/AppoinmentSystem/BookAppointment.jsx
Labels: feature

#15 add Home Page
  src/App.jsx
  src/components/AppoinmentSystem/Home.jsx
  src/components/AppoinmentSystem/Navbar.jsx
  src/pages/AppointmentSystem/UserHome.jsx
Labels: feature

#16 It22202468/user management
  .gitignore
  src/App.jsx
  src/Services/patientService.js
  src/components/AppoinmentSystem/Home.jsx
  src/pages/UserManagement/AdminDashboard.jsx
  src/pages/UserManagement/DoctorDashboard.jsx
  src/pages/UserManagement/ForgotPassword.jsx
  src/pages/UserManagement/Login.jsx
  src/pages/UserManagement/NurseDashboard.jsx
  src/pages/UserManagement/PatientDashboard.jsx
  src/pages/UserManagement/PatientLogin.jsx
  src/pages/UserManagement/PatientProfile.jsx
  src/pages/UserManagement/ResetPassword.jsx
  src/pages/UserManagement/Signup.jsx
  src/pages/UserManagement/VerifyOTP.jsx
Labels: feature
